version: "3.9"

services:
  devopsdb:
    container_name: db-cont
    image: db-image
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD=devopspassword
    volumes:
      - userdata:/var/lib/mysql

  application:
    container_name: app-cont
    image: app-image
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb


volumes:
  userdata:
